app:
  name: "Tiyago"
  host: "0.0.0.0"
  port: "7000"
  environment: "local"
databases:
- connection: "postgreSql"
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  password: "postgres"
  database: "tiyago"
  usage: "Main databases!"
jwt:
  secret_key: "TiyagoSecretKey!"
  refresh_secret_key: "TiyagoRefreshSecretKey!"
