app:
  name: "Apps"
  service: "http"
  host: "0.0.0.0"
  port: "7000"
  environment: "local"
databases:
- connection: "postgreSql"
  host: "127.0.0.1"
  port: 5430
  user: "postgres"
  password: "mysecretpassword"
  database: "go-rest-api"
  usage: "Main databases!"
jwt:
  secretKey: "dHgpUE99P299bks4a2NZS2leKlJwfSQveSdIZ0NYU05zZk1lLnF3Ryg9fmddNnViMEouRSVqeF5fc0RubC44"
