app:
  name: "Apps"
  service: "http"
  host: "0.0.0.0"
  port: "7000"
  environment: "production"
databases:
- connection: "postgreSql"
  host: ""
  port: 5432
  user: "postgres"
  password: ""
  database: ""
  usage: "Main databases!"
